### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sarin-dotin** [kaiser-9527/hubble#1]
![Screenshot from 2022-12-27 15-07-32](https://user-images.githubusercontent.com/66765575/209646336-3cf8df21-d557-4d75-9d14-48b6c1a6088c.png)
![Screenshot from 2022-12-27 15-07-09](https://user-images.githubusercontent.com/66765575/209646366-fe3e09f0-ab4b-464e-8b85-748e82483560.png)

**Comment by kaiser-9527** [comment]
Thank you for bringing up the bug.
I've already fixed it. You can try again

https://github.com/kaiser-9527/hubble/commit/bb33938a571905ca4edd59f8db5f94d7c1e0b1c5
