### ISSUE TITLE
[Feature Request] Escape tags white space

### ISSUE THREAD

**Issue by ziloen** [kaiser-9527/hubble#2]
![image](https://user-images.githubusercontent.com/34268416/210169886-3fd36d20-f9d3-4806-a52d-588e0c08b016.png)

Maybe something like this: `tag:"Tag with white space"`, this is how github labels looks like
---
Label with white space
![image](https://user-images.githubusercontent.com/34268416/210170037-d2fb4d30-db15-4271-be20-f07bee48812a.png)
Labels without white space
![whitout white space](https://user-images.githubusercontent.com/34268416/210170073-8b074abb-7ded-46ec-9e43-0b4626564c73.png)

**Comment by kaiser-9527** [comment]
Thanks for your suggestion. Welcome to try again

**Comment by ziloen** [comment]
Seems like it works. Thank you so much!
