### ISSUE TITLE
通过vercel自部署 ,需要supabase ddl语句

### ISSUE THREAD

**Issue by louyongjiu** [kaiser-9527/hubble#3]
我通过vercel自部署，链接至自己的supabase  ，但现在缺少数据库初始化的语句
页面操作，数据无法正常保存

**Comment by kaiser-9527** [comment]
实际上，除了初始化语句，你还会需要database functions。后端部分后面会陆续开源出来。

**Comment by louyongjiu** [comment]
最近一直在找这种工具
期待后续开源部分

**Comment by kaiser-9527** [comment]
非常抱歉，因为一些原因，这个项目搁置了许久。最近进行一次大升级 #7 ，已经把supabase的内容开源了。
