### ISSUE TITLE
Bug: the deleted tag reappears after data is synchronized

### ISSUE THREAD

**Issue by imyuanx** [kaiser-9527/hubble#6]
I have a tag: `tools` and just one repo use it, when I delete this tag from my repo and sync data, `tools` is reshow

**Comment by kaiser-9527** [comment]
Thanks.
This is really a legacy issue. This project will be upgraded or optimized in the near future. This will be fixed at that time

**Comment by kaiser-9527** [comment]
This upgrade has solved this problem #7 , welcome to try again,

**Comment by imyuanx** [comment]
Cool, It worked properly 👍
