### ISSUE TITLE
Bug: 当账号星标仓库的数量比较大时, 请求/api/github-starred-repo 超过10秒,返回超时报错

### ISSUE THREAD

**Issue by louyongjiu** [kaiser-9527/hubble#8]
![image](https://github.com/kaiser-9527/hubble/assets/16408477/8d62c9e4-bd65-4b7a-ba60-dbe518e1915b)

**Comment by kaiser-9527** [comment]
之前没考虑过数据量大的问题，现在把route handle 改成客户端请求了
